//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleMVC.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankData
    {
        public int BankId { get; set; }
        public string BankName { get; set; }
        public string TrnAmt { get; set; }
        public int AccountType { get; set; }
        public string IFSCCode { get; set; }
    }
}
