//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleMVC.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionMaster
    {
        public int TransactionId { get; set; }
        public string TransText { get; set; }
        public string TransDetails { get; set; }
    }
}
